name: Action
on: [push]

jobs:
  betterscan_job:
   runs-on: ubuntu-latest
   name: Betterscan scan job
   steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses:  topcodersonline/betterscancustom@v1
